name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r api/requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          ruff api
          black --check api
      - name: Tests
        run: pytest
      - name: Security audit
        run: pip-audit -r api/requirements.txt
      - name: NPM audit
        working-directory: web
        run: npm audit --production
      - name: TruffleHog
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          only_verified: true
